#!/bin/bash
#
# installs things.

function installMacSoftwares() {
# set git credential helper
git config --global credential.helper osxkeychain

echo 'Install homebrew'
echo '----------------'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "${HOME}/.zprofile"
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'Install programs with brew'
echo '----------------'
brew bundle -v
}

function installLinuxSoftwares() {
echo "Linux"
}

function checkOs() {
# check os
os="`uname`"

if [[ $os == 'Darwin' ]]
then
installMacSoftwares
elif [[ $os == 'Linux' ]]
then
installLinuxSoftwares
fi
}

function install() {
# ask password beforehand
sudo -v

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/.zshrc $HOME/.zshrc

# Add global gitignore
ln -s $HOME/.dotfiles/.gitignore_global $HOME/.gitignore_global
git config --global core.excludesfile $HOME/.gitignore_global
git config --global core.editor "/usr/bin/vim"
git config --global init.defaultBranch main

# Install essential software's
checkOs

# Create a Project directory
mkdir $HOME/Project

# Symlink starship config
mkdir -p ~/.config
ln -s $HOME/.dotfiles/starship.toml $HOME/.config/starship.toml

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
}


echo 'Install .dotfiles'
echo '------------------'
echo 'This will reset your terminal. Are you sure you want to do this? (y/n) '
read -p 'Answer: '  reply

if [[ $reply =~ ^[Yy]$ ]]
then
install
fi
